### ISSUE TITLE
PRACTICA DE MOPROSOFT JUDITH REYNA CRUZ SANTIAGO

### ISSUE THREAD

**Issue by JudithReynaCS** [SistemasTecTlaxiaco/actividad-5-practica-de-moprosoft-equipo-jamm#2]
[PRACTICA_MOCROSOFT.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-practica-de-moprosoft-equipo-jamm/files/12807678/PRACTICA_MOCROSOFT.pdf)

**Comment by Aricel117** [comment]
Calificacion: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
